#!/bin/bash

docker run -it -v $(pwd):$(pwd) \
-w $(pwd) --network host \
-e RMW_IMPLEMENTATION \
-d --rm \
--name sam6d_ros2_publisher \
keti_planning:latest python3 sam6d_ros2_publisher.py

docker run -it -v $(pwd):$(pwd) \
-w $(pwd) --network host \
-e RMW_IMPLEMENTATION \
-d --rm \
--name sam6d_tf_broadcaster \
keti_planning:latest python3 sam6d_ros2_camera_braodcaster.py \
--ros-args --param npz_path:="./camera_036322250488_extrinsics.npz" \
--param parent_frame:="xarm_device"

#OBJECT_DIR="myObject/dominoSugar"
#CAD_FILE="dominoSugar.ply"

#OBJECT_DIR="myObject/tomatoSoup"
#CAD_FILE="tomatoSoup.ply"
ROOT="${HOME}/ycb_ws/Fork_SAM-6D/SAM-6D"

#OBJECT_DIR="myObject/S_block"
#CAD_FILE="S_block.ply"

OBJECT_DIR="myObject/I_block_large"
CAD_FILE="I_block_large.ply"
#OBJECT_DIR="myObject/2_block"
#CAD_FILE="2_block.ply"
#
conda run -n sam6d python sam6d_tracker.py \
   --segmentor_model fastsam \
  --output_dir "$ROOT/Data/$OBJECT_DIR/outputs" \
  --cad_path "$ROOT/Data/$OBJECT_DIR/$CAD_FILE" \
  --det_score_thresh 0.5 \
  --visualize

docker stop sam6d_ros2_publisher
docker stop sam6d_tf_broadcaster
